This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file /Users/manuel/Dropbox/04_KIT/02_Master/04_Master Thesis/09_LaTeX/Masterarbeit/.texpadtmp/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/manuel/Dropbox/04_KIT/02_Master/04_Master Thesis/09_LaTeX/Masterarbeit/.texpadtmp/thesis.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file /Users/manuel/Dropbox/04_KIT/02_Master/04_Master Thesis/09_LaTeX/Masterarbeit/.texpadtmp/thesis.acr....done (9 lines written, 0 warnings).
Output written in /Users/manuel/Dropbox/04_KIT/02_Master/04_Master Thesis/09_LaTeX/Masterarbeit/.texpadtmp/thesis.acr.
Transcript written in /Users/manuel/Dropbox/04_KIT/02_Master/04_Master Thesis/09_LaTeX/Masterarbeit/.texpadtmp/thesis.alg.
